### ISSUE TITLE
Click outside modal to close

### ISSUE THREAD

**Issue by baohx2000** [diegoddox/react-redux-modal#1]
This would be an extra option that would be passed to `modal.add`, probably a boolean `closeOnOutsideClick`, default to `false` to keep current usage.

**Comment by diegoddox** [comment]
@baohx2000 
Sounds good but I don't know when I will be able to implement.

**Comment by baohx2000** [comment]
I may have time to PR something this weekend.

**Comment by diegoddox** [comment]
@baohx2000 
Feel free, jut clone the repo `npm i` `npm start` and you'r read to rock! ;)

**Comment by baohx2000** [comment]
@diegoddox fontello seems to be missing from the repo.

**Comment by diegoddox** [comment]
This is a bug with the `min.css` version, it works fine if you use the normal (css)[http://diegoddox.github.io/react-redux-modal/0.1.0/react-redux-modal.css].

**Comment by baohx2000** [comment]
The css is expecting fontello to be in a fonts folder.  Should I add it?  BTW, thanks for the merge!
`font-face {
  font-family: 'fontello';
  src: url('../fonts/fontello.eot?10665767');
  src: url('../fonts/fontello.eot?10665767#iefix') format('embedded-opentype'), url('../fonts/fontello.woff?10665767') format('woff'), url('../fonts/fontello.ttf?10665767') format('truetype'), url('../fonts/fontello.svg?10665767#fontello') format('svg');`

**Comment by diegoddox** [comment]
No, you don't need to add the fonts, they are on the github page. Try include the no minify version and see if works for you?

**Comment by baohx2000** [comment]
I'm just saying that `npm start` will not work until this is resolved.  Will make another issue for it.
