### ISSUE TITLE
Handle browser back navigation

### ISSUE THREAD

**Issue by bstst** [diegoddox/react-redux-modal#5]
If I were to use this on mobile and I were to open a modal, navigating back should, theoretically, close the modal. How would you handle that scenario here?

**Comment by diegoddox** [comment]
@bstst depend on how you have setup your project.
But I will assume that you are using in your project `react-router-redux` and `react-router` if so here is what I think you can do.

Every time the page change you can clean the `react-redux-modal` `state`

```
import {modal} from 'react-redux-modal';
// this you should have if you're using react-router-redux
const history = syncHistoryWithStore(browserHistory, store);

let lastLocation = null;

history.listen(location => {
 if (lastLocation != location. pathname) {
  modal.clear();
 }
 lastLocation = location. pathname;
});
```

**Comment by diegoddox** [comment]
@bstst I will close this issue as it is not a `bug` but rather a personal question on how to solve this on your project, but feel free to ask anything and please let me know if the code above has helped you.
