### ISSUE TITLE
Auto Focus?

### ISSUE THREAD

**Issue by danielstern** [diegoddox/react-redux-modal#9]
It should be possible to automatically focus a selected modal element when it opens.

It should be possible to focus a specific other element when the modal closes.

**Comment by diegoddox** [comment]
Yes it is possible, what is your issue!

**Comment by danielstern** [comment]
I currently have a modal with an OK button. When that modal opens, I want the OK button to be focused. Is there a code example that does this?

**Comment by diegoddox** [comment]
Just add the `autofocus` in your button.
ex: `<button autofocus>my button</button>`

**Comment by danielstern** [comment]
@diegoddox Sounds good, actually what was needed was

`<button autoFocus={true}>My button </button>`

This also does not quite work

**Comment by danielstern** [comment]
Actually, this only seems to work on select inputs. Not on buttons. Is there an example with a working autoFocus on a button I can work off of?

**Comment by diegoddox** [comment]
Your question has nothing to do with the `repo` but try this.

```
componentDidMount(){
   this.refs.nameOfButon.getDOMNode().focus(); 
}

render() {
   return <button ref="nameOfButon">my button</button>;
}
```

**Comment by danielstern** [comment]
Sure it does. 

Since my app is using the Redux pattern, components can't have ref or state. So, this doesn't work. 

The autofocus value on the button should just work when placed on a modal from this repo.

**Comment by diegoddox** [comment]
no, and you can still use `refs` and `states` under `redux` https://github.com/reactjs/redux/issues/1287
